// database:[movename, list_of_muscles_involved]
var moves = [
  ["penkkipunnerrus", ["ojentajat", "rinta"]],
  ["hauiskääntö", ["hauis"]],
  ["penkkipunnerrus ojentajat", ["ojentajat"]],
  ["ranskalainen punnerrus", ["ojentajat"]],
  ["vatsarutistus", ["vatsalihakset"]],
  ["kyykky", ["reidet", "pakarat"]],
  ["askelkyykky", ["reidet", "pakarat"]],
  ["penkkipunnerrus kp", ["rinta"]],
  ["vipunostot sivuille", ["sivuolkapäät"]],
  ["ylätalja, leveä ote eteen", ["selkä"]],
  ["pystypunnerrus kp", ["etuolkapäät"]],
  ["vinopenkki kp", ["rinta"]],
  ["ojentajat taljassa", ["ojentajat"]],
  ["dippi penkillä takana, jalat maassa", ["ojentajat"]],
  ["hauiskääntö vinopenkillä", ["hauis"]],
  ["kulmasoutu kp", ["selkä"]],
  ["jalkaprässi", ["reidet", "pakarat"]],
  ["vatsarutistus kuntopallolla", ["vatsa"]],
  ["alasoutu", ["selkä"]],
  ["ristikkäistalja", ["rinta"]],
  ["pystysoutu", ["sivuolkapäät"]],
  ["hauiskääntö taljassa", ["hauis"]],
  ["reisilaite", ["reidet"]],
  ["vatsalihaslaite", ["vatsalihakset"]],
  ["pohjelaite istuen", ["pohje"]],
  ["pohkeet jalkaprässissä", ["pohje"]],
  ["jalan nosto koukussa selällään", ["syvät vatsalihakset"]],
  ["jalan nosto suorana selällään", ["syvät vatsalihakset"]],
  ["vatsalihakset kierto", ["kyljet"]],
  ["vatsalihakset kierto laitteella", ["kyljet"]]];

// put these in ascending order of intensity
var series = ["3x15", "3x10", "5x5"];